[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "https://interviewbot-rjsi.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://interviewbot-rjsi.onrender.com/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
